Param( $buildconf="Release", $clean=1 )

& "$PSScriptRoot\build-win.ps1" $buildconf $clean

# 1. Publish all projects
dotnet publish src\Dirigent.CLI\Dirigent.CLI.csproj -f net8.0-windows -r win-x64 --no-self-contained -o publish\Dirigent.CLI\win-x64\$buildconf
dotnet publish src\Dirigent.Agent.WinForms\Dirigent.Agent.WinForms.csproj -f net8.0-windows -r win-x64 --no-self-contained -o publish\Dirigent.Agent.WinForms\win-x64\$buildconf
dotnet publish src\Dirigent.Gui.ImGui\Dirigent.Gui.ImGui.csproj -f net8.0-windows -r win-x64 --no-self-contained -o publish\Dirigent.Gui.ImGui\win-x64\$buildconf
dotnet publish src\Dirigent.Agent.Starter\Dirigent.Agent.Starter.csproj -f net8.0-windows -r win-x64 --no-self-contained -o publish\Dirigent.Agent.Starter\win-x64\$buildconf

# 2. Prepare Release folder
$releasePath = "release\win-x64\$buildconf"
New-Item -ItemType Directory -Force -Path $releasePath

# 3. Merge published files via Robocopy
robocopy publish\Dirigent.Gui.ImGui\win-x64\$buildconf $releasePath /E
robocopy publish\Dirigent.CLI\win-x64\$buildconf $releasePath /E
robocopy publish\Dirigent.Agent.WinForms\win-x64\$buildconf $releasePath /E
robocopy publish\Dirigent.Agent.Starter\win-x64\$buildconf $releasePath /E

Copy-Item "$PSScriptRoot\VersionStamp.txt" -Destination $releasePath -Force

# Cleanup Satellite Resources ---

"Cleaning up unwanted language folders in $releasePath..."

# List of common language codes generated by .NET/NuGet dependencies
$excludedLangs = @(
    "cs", "de", "es", "fr", "it", "ja", "ko", "pl", "pt-BR", "ru", "tr", "zh-Hans", "zh-Hant"
)

foreach ($lang in $excludedLangs) {
    $target = Join-Path $releasePath $lang
    if (Test-Path $target) {
        Write-Host "Removing: $lang" -ForegroundColor Cyan
        Remove-Item -Recurse -Force $target
    }
}

"Cleanup complete."

