<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <Product>Dirigent</Product>
    <Version Condition="'$(RELEASE_VERSION)' != ''">$(RELEASE_VERSION)</Version>
    <Authors>pjanec</Authors>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AssemblyName>Dirigent.Agent.Starter</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dirigent.Agent.Core\Dirigent.Agent.Core.csproj" />
  </ItemGroup>

</Project>
