<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>Dirigent.TestApp</AssemblyName>
    <RootNamespace>Dirigent.TestApp</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
